-- CreateTable
CREATE TABLE `Product` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `units` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Product_title_key`(`title`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Order` (
    `id` VARCHAR(191) NOT NULL,
    `createdBy` VARCHAR(191) NOT NULL,
    `productId` VARCHAR(191) NOT NULL,
    `quantity` DOUBLE NOT NULL,
    `created` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ordered` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `invoiced` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `payed` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `shipped` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `received` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Order` ADD CONSTRAINT `Order_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
